### ISSUE TITLE
[TEST CASE] Concurrency Safety

### ISSUE THREAD

**Issue by syde91** [fathimaali/go-observable-cache#1]
As a developer, I want to ensure my package is concurrent safe. 

- [ ] Spawn 5000 Goroutines, update one key, By incrementing the value by one. And ensure that after all the go routines are done, the value is 5000 or 4999.

**Comment by fathimaali** [comment]
this was implemented along with Issue #4 
also, removed the hard validation for 5000.
test pass if pgm runs, fail if we have concurrent read or write into the map
